Repository lblod/frontend-validation-tool, pull requests merged in 2024-05, with the labels that each got.

#7 Quality of life + Bug Fixes
  app/components/subject.ts
  app/constants/document-types.ts
  app/controllers/application.ts
  app/controllers/document-review.ts
  app/controllers/document-upload.ts
  app/controllers/validation-results.ts
  app/routes/document-review.ts
  app/routes/document-upload.ts
  app/routes/validation-results.ts
  app/services/document.ts
  app/styles/app.scss
  app/templates/document-upload.hbs
  app/templates/validation-results.hbs
  package-lock.json
  package.json
  yarn.lock
Labels: bug, enhancement

#13 Resize buttons
  app/templates/document-review.hbs
Labels: enhancement

#14 "Gevonden URI" Label
  app/components/alert-section.hbs
  app/components/class-collection.hbs
  app/components/copy-to-clipboard.hbs
  app/components/copy-to-clipboard.ts
  app/components/custom-accordion.hbs
  app/components/recursive-entry.hbs
  app/components/root-subject.hbs
  app/components/subject-property.hbs
  app/styles/app.scss
  app/templates/validation-results.hbs
  package.json
  tests/integration/components/copy-to-clipboard-test.ts
  yarn.lock
Labels: enhancement

#17 Put maturity and legend next to eachother
  app/styles/app.scss
  app/styles/shame.scss
  app/templates/validation-results.hbs
  config/environment.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#16 Add Validation Label to Main Validation Block with Dynamic Status Update + Format iso dates in validation tool
  app/components/custom-accordion.hbs
  app/components/recursive-entry.hbs
  app/components/recursive-entry.ts
  app/components/root-subject.hbs
  app/components/root-subject.ts
  app/components/subject-property.hbs
  app/components/subject-property.ts
  app/helpers/formatValue.ts
  app/templates/validation-results.hbs
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#15 Update docs with frontend-validation-tool and use app-validation-tool
  .gitignore
  README.md
  app/app.ts
  app/components/recursive-entry.ts
  app/components/root-subject.ts
  app/config/environment.d.ts
  app/controllers/document-review.ts
  app/controllers/document-upload.ts
  app/controllers/validation-results.ts
  app/index.html
  app/router.ts
  app/routes/document-upload.ts
  app/routes/validation-results.ts
  app/services/document.ts
  config/environment.js
  package.json
  tests/index.html
  tests/integration/components/accordion-test.ts
  tests/integration/components/alert-section-test.ts
  tests/integration/components/dynamic-link-test.ts
  tests/integration/components/recursion-entry-test.ts
  tests/integration/helpers/file-queue-test.ts
  tests/integration/helpers/format-entry-name-test.ts
  tests/integration/helpers/is-array-test.ts
  tests/integration/helpers/is-single-string-in-array-test.ts
  tests/integration/helpers/is-string-test.ts
  tests/integration/helpers/is-uri-test.ts
  tests/test-helper.ts
  tests/unit/controllers/application-test.ts
  tests/unit/controllers/document-review-test.ts
  tests/unit/controllers/document-upload-test.ts
  tests/unit/routes/application-test.ts
  tests/unit/routes/document-review-test.ts
  tests/unit/routes/document-upload-test.ts
  tests/unit/routes/proxy-test.ts
  tests/unit/routes/validation-results-test.ts
  tests/unit/services/document-test.ts
  tsconfig.json
Labels: documentation, enhancement

#19 Add examples to ui
  app/components/alert-section.hbs
  app/components/root-subject.ts
  app/components/subject-property.hbs
  app/components/subject-property.ts
  app/controllers/document-upload.ts
  app/controllers/validation-results.ts
  app/services/document.ts
  app/styles/app.scss
  package-lock.json
  package.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#20 Property/Subject Diff (Tooltip)
  app/components/recursive-entry.hbs
  app/components/subject-property.hbs
  app/styles/shame.scss
Labels: enhancement

#22 Split up Correct/Volledig
  app/components/custom-accordion.hbs
  app/components/recursive-entry.hbs
  app/components/recursive-entry.ts
  app/components/root-subject.hbs
  app/components/root-subject.ts
  app/components/subject-property.hbs
  app/components/subject-property.ts
  app/services/document.ts
  app/styles/shame.scss
  app/templates/validation-results.hbs
Labels: enhancement

#27 Invalid filter
  app/controllers/validation-results.ts
  app/routes/validation-results.ts
  app/services/document.ts
  app/templates/validation-results.hbs
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement
